name: coUemoticons
description: Emoticons for the client
version: 2.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  libld:
      git:
        ref: master
        url: git://github.com/ChildrenOfUr/libld.git

dev_dependencies:
  build_runner: '>=0.8.10 <2.0.0'
  build_web_compilers: '>=0.3.6 <2.0.0'