name: coUemoticons
description: Emoticons for the client
version: 2.0.1
dependencies:
  browser: any
  libld:
      git:
        ref: master
        url: git://github.com/ChildrenOfUr/libld.git
  edit_distance: "^0.3.0"
