name: coUemoticons
description: Emoticons for the client
version: 3.0.1

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  libld:
    git:
      url: git://github.com/ChildrenOfUr/libld.git
      ref: dart-2
